### PR TITLE
Out of cash

### PR DESCRIPTION
**Pull request by IDisposable**
Venture capitalist requested I add this.

### CODE REVIEW

**Comment by wholroyd** [comment]
+1

**Comment by bobthecow** [comment]
:+1:

**Comment by joho** [comment]
On point: :+1:

**Comment by IDisposable** [comment]
Woot... (especially given our start-up ran out of cash two weeks ago)

**Comment by joho** [comment]
@IDisposable I've been in that spot too - condolences and best of luck with whatever comes next.

**Comment by IDisposable** [comment]
Thanks.. already landed elsewhere... we have a MVP+20 version with no money to market it. :(

**Comment by superhighfives** [comment]
+1, feelings

**Pull request merged**
