### PR TITLE
🤌

### PR DESCRIPTION
**Pull request by kzlsakal**
🤌

### CODE REVIEW

**Comment by StackUndertow** [comment]
Did someone dump this on hackernews or something?

**Comment by tclancy** [comment]
[Yup](https://news.ycombinator.com/item?id=27522353)

**Comment by StackUndertow** [comment]
Whelp, was fun while it lasted >.<

**Comment by virtadpt** [comment]
Yuuuuuuuuuucckk.....

**Comment by kzlsakal** [comment]
For anyone wasn't able to see the character, it was this: https://emojipedia.org/pinched-fingers/

**Pull request closed without merging**
