### PR TITLE
Fix 736, add 738.

### PR DESCRIPTION
**Pull request by ostera**
Not much else to say 📦 Thanks for this 🌈

### CODE REVIEW

**Comment by harleyknd1** [comment]
You do realize you put 735 after 736 and have a duplicate 738? 
I'm not entirely sure if this is part of the "joke" or just a "rtfm" error

**Comment by ostera** [comment]
The race conditions make `736` be listed before.

And `738` is duplicated because it's _exactly-once_ delivery.

Just part of the jokes!

**Comment by AsParallel** [comment]
thatsthejoke.jpg

**Comment by joho** [comment]
I like this.

**Pull request merged**
